### PR TITLE
Output original cmd on script run

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by holgerd77** [comment]
Tested one command (`coverage`) manually by injecting into `ethereumjs-common`. Approach generally works.

**Comment by s1na** [comment]
I tried to inject `config-prettier/cli/format.sh` into `ethereumjs-common` manually and got this weird error:

```
[ethereumjs-config-prettier -> format]: prettier --list-different '**/*.{ts,json,md}'
[error] No matching files. Patterns tried: '**/*.{ts,json,md}' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

Investigating more to see if I can find the issue.

**Comment by holgerd77** [comment]
Can confirm. Then it's probably not operating on the correct path?

**Comment by holgerd77** [comment]
Ah no, it's actually working when command is slightly changed to `prettier --list-different **/*.{ts,json,md}` (so leaving the single quoting).

Ah, seems I have to do a manual test on all this commands, otherwise it will get too risky.

Bit annoying, but will do and give re-confirmation respectively do some changes.

**Comment by s1na** [comment]
I tried with replacing `exec` with `eval` and it seems to work. I think it might be that `exec` is interpreting `$CMD` as a single command and doesn't pass the options correctly. `exec` works if the command is stored like `CMD=$(prettier...)` (but then the echo doesn't work.

**Comment by holgerd77** [comment]
Hmm, do we still get the benefits we wanted to have by introducing `exec` as suggested by @whymarrh ("maybe using exec to offload input, error, and signal handling to prettier")?

**Comment by holgerd77** [comment]
Hmm, the `coverage` command goes into some totally strange recursive calling of the separate commands again and again, no matter if using `eval` or `exec`.

Might be postponing this, sorry, didn't want this to take so much time/attention. Thought it would be more of a minor but useful side-change.

**Comment by s1na** [comment]
Yeah agree it would be useful. It's probably one of those cases where a tiny change would fix it, but one has to first figure out the exact issue.

**Comment by whymarrh** [comment]
Yeah, I do maintain that there's a significant upside to using `exec` _where we can_, as that will relieve us from having to handle errors in the scripts. We can use exec here with the commands as a string as they'll first be interpolated by the shell, if they're not quoted and allowed to be expanded by the shell. I don't think we'll be able to use redirections without using something like `eval`.

**Comment by whymarrh** [comment]
That said, we can opt to not use `exec` and handle/ignore errors as needed

**Comment by holgerd77** [comment]
I did another search and stumbled over the solution [here](https://stackoverflow.com/a/5750463). Updated and tested by manually injecting to all commands on the common library. This worked fine without (apparent/visible) side effects, provides output like this:

```shell
$ npm run format

> ethereumjs-common@1.1.0 format /PATH/ethereumjs-common
> ethereumjs-config-format

+ exec prettier --list-different '**/*.{ts,json,md}'
```
(last line is new)

This is now open for another review.

**Comment by holgerd77** [comment]
Thanks, published new versions `v1.1.1`.

**Pull request merged**
